### ISSUE TITLE
Glowing doesn't work anymore

### ISSUE THREAD

**Issue by Disidious** [CodeReviewer14/Cyber-77-Synthwave-VSCode#1]
The enable glow command for some reason doesn't work anymore for me idk why.
For it to work I have to uninstall and install the theme again each time I open vs code.

The glow works fine on Robb Owen's Synthwave '84 theme tho.

**Comment by CodeReviewer14** [comment]
It should work now if you update to the latest version in the Marketplace (0.0.19).

**Comment by Disidious** [comment]
I uninstalled and installed multiple times which should update the version I already had but still not working.

**Comment by CodeReviewer14** [comment]
The glow indeed seemed to be broken after the latest VSCode update that took a while to initialize the styles content.
This issue was just addressed and version 0.0.19 update of this theme works for me with the latest VSCode update now after a window reload.
